"""Tool: send invitation emails to vendors via Resend.

The email is composed from the inputs, persisted to Supabase as the audit-trail
source of truth, and (best-effort) actually delivered via the Resend API.
"""

import os
import logging

# Ensure .env is loaded before reading env vars
from dotenv import load_dotenv
load_dotenv()

from app.services.supabase_client import supabase_service

# Resend setup
try:
    import resend
    _RESEND_API_KEY = os.getenv("RESEND_API_KEY")
    if _RESEND_API_KEY:
        resend.api_key = _RESEND_API_KEY
        _RESEND_ENABLED = True
        logging.info("Resend enabled with API key (length=%d)", len(_RESEND_API_KEY))
    else:
        _RESEND_ENABLED = False
        logging.warning("RESEND_API_KEY not found in environment - emails will be simulated")
except ImportError:
    _RESEND_ENABLED = False
    logging.warning("resend module not installed - emails will be simulated")

_RESEND_FROM = os.getenv("RESEND_FROM_EMAIL", "onboarding@resend.dev")
_logger = logging.getLogger(__name__)


def send_invitation_email(
    job_id: str,
    vendor_name: str,
    vendor_email: str,
    rfp_title: str,
    reference_id: str,
    predicted_bid_pkr: float,
    submission_deadline_iso: str,
    portal_url: str,
    issuing_organization: str,
) -> dict:
    """Send an invitation email to a single vendor and persist to sent_emails."""
    subject = f"Invitation to Bid: {rfp_title} (Ref: {reference_id})"
    body_text = (
        f"Dear {vendor_name} Team,\n\n"
        f"You are invited to participate in the procurement process for: {rfp_title}.\n\n"
        f"Reference ID: {reference_id}\n"
        f"Issuing Organization: {issuing_organization}\n"
        f"Submission Deadline: {submission_deadline_iso}\n"
        f"Tender Portal: {portal_url}\n\n"
        f"Based on historical bidding patterns, the expected bid range positions your "
        f"organization's typical pricing (approximately PKR {predicted_bid_pkr:,.0f}) "
        f"competitively for this opportunity.\n\n"
        f"Please refer to the attached RFP document for full eligibility criteria, "
        f"evaluation methodology, and mandatory PPRA clauses.\n\n"
        f"For further correspondence, please contact the procurement officer named in the RFP document.\n\n"
        f"Sincerely,\n"
        f"{issuing_organization} Procurement\n"
        f"(no-reply)"
    )

    body_html = f"""
    <div style="font-family: Inter, Arial, sans-serif; max-width: 640px; margin: 0 auto; padding: 24px; color: #0F2A4A;">
      <h2 style="color: #0F2A4A; margin-bottom: 8px;">Invitation to Bid</h2>
      <p style="color: #16A34A; font-weight: 600; margin-top: 0;">Reference ID: {reference_id}</p>
      <p>Dear <strong>{vendor_name}</strong> Team,</p>
      <p>You are invited to participate in the procurement process for:</p>
      <p style="background: #F1F5F9; padding: 12px 16px; border-radius: 8px; font-weight: 600; font-size: 16px;">
        {rfp_title}
      </p>
      <table style="width:100%; margin: 16px 0; border-collapse: collapse;">
        <tr><td style="padding: 6px 0; color: #475569;">Issuing Organization</td><td style="padding: 6px 0;"><strong>{issuing_organization}</strong></td></tr>
        <tr><td style="padding: 6px 0; color: #475569;">Submission Deadline</td><td style="padding: 6px 0;"><strong>{submission_deadline_iso}</strong></td></tr>
        <tr><td style="padding: 6px 0; color: #475569;">Tender Portal</td><td style="padding: 6px 0;"><a href="{portal_url}" style="color: #16A34A;">{portal_url}</a></td></tr>
        <tr><td style="padding: 6px 0; color: #475569;">Predicted bid (your typical range)</td><td style="padding: 6px 0;"><strong>PKR {predicted_bid_pkr:,.0f}</strong></td></tr>
      </table>
      <p>Please refer to the attached RFP document for full eligibility criteria, evaluation methodology, and mandatory PPRA clauses.</p>
      <p style="margin-top: 32px; color: #64748B; font-size: 13px;">
        Sincerely,<br>
        {issuing_organization} Procurement Office<br>
        <em>This is an automated invitation generated by the RFP Agent System.</em>
      </p>
    </div>
    """

    # 1. Persist to Supabase first — audit trail source of truth
    row = supabase_service.save_sent_email(
        job_id=job_id,
        to_email=vendor_email,
        to_name=vendor_name,
        subject=subject,
        body=body_text,
    )

    # 2. Attempt real delivery via Resend (best effort)
    delivery_status = "simulated"
    delivery_id = None
    delivery_error = None

    _logger.info(f"send_invitation_email called for {vendor_email}, _RESEND_ENABLED={_RESEND_ENABLED}")

    if _RESEND_ENABLED:
        try:
            send_response = resend.Emails.send({
                "from": _RESEND_FROM,
                "to": [vendor_email],
                "subject": subject,
                "html": body_html,
                "text": body_text,
            })
            delivery_id = send_response.get("id") if isinstance(send_response, dict) else None
            delivery_status = "delivered"
            _logger.info(f"Resend delivered email to {vendor_email} (id={delivery_id})")
            print(f"[RESEND] Sent to {vendor_email}, id={delivery_id}")
        except Exception as exc:
            delivery_status = "delivery_failed"
            delivery_error = str(exc)
            _logger.warning(f"Resend delivery failed for {vendor_email}: {exc!r}")
            print(f"[RESEND ERROR] Failed for {vendor_email}: {exc!r}")
    else:
        print(f"[RESEND SKIPPED] _RESEND_ENABLED=False for {vendor_email}")

    return {
        "email_id": row["id"],
        "to_email": vendor_email,
        "to_name": vendor_name,
        "subject": subject,
        "status": row.get("status", "sent"),
        "delivery_status": delivery_status,
        "delivery_id": delivery_id,
        "delivery_error": delivery_error,
    }